version: "3.4"
networks:
services:   
  browser:
    image: rebelplutonium/browser:${BROWSER_VERSION}
    volumes:
      - /tmp/.X11-unix/X0:/tmp/.X11-unix/X0:ro
    environment:
      - DISPLAY
    labels:
      expiry: ${EXPIRY}